app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "icloud.log"
  credentials:
    # iCloud drive username
    username: "marco@visin.ch"
    # Retry login interval - default is 10 minutes
    retry_login_interval: 600
  # Drive destination
  root: "icloud"
  smtp:
    ## If you want to recieve email notifications about expired/missing 2FA credentials then uncomment
    # email: "user@test.com"
    ## optional, to email address. Default is sender email.
    # to: "receiver@test.com"
    # password:
    # host: "smtp.test.com"
    # port: 587
    # If your email provider doesn't handle TLS
    # no_tls: true
photos:
  destination: "photos"
  remove_obsolete: true
  sync_inteval: 172800
  workers: 10
  filters:
    #albums:
    #    - "Capodanno 2016: Austria"
    file_sizes: # valid values are original, medium and/or thumb
        - "original"



